### ISSUE TITLE
Implementare la funzionalità in menu functionality component che mostri le funzionalità accessibili con dei dati permessi

### ISSUE THREAD

**Issue by Cis8** [qb-team/Stalker-Admin#139]
Un'idea può essere di mettere degli ngIf nel template html che controllino se mostrare o nascondere una funzionalità in base ai privilegi dell'amministratore per l'organizzazione attualmente selezionata nella menubar.
Avremo quindi che menu-functionality si sottoscrive a un observable priviledge in data service che rappresenta il privilegio per l'attuale organizzazione. Quando l'utente seleziona un altra organizzazione allora verrà emesso un evento che cambia il valore del privilegio in data service e quindi le funzionalità esposte da menu functionality.
Per ottenere i privilegi dell'attuale organizzazione per poi emetterli in data service, menubar dovrà chiedere o conoscere i privilegi dell'utente per l'organizzazione mostrata nel menu a tendina in alto.

**Comment by pheasant98** [comment]
creato funzioni apposite per la gestione della visualizzazione delle funzionalità a seconda dei permessi, ora vengono mostrate solo le funzionalità che sono permesse all'amministratore
