### ISSUE TITLE
Bug da risolvere

### ISSUE THREAD

**Issue by pheasant98** [qb-team/Stalker-Admin#144]
**Bug da risolvere**

- [x] Login LDAP, se si sbaglia password o si mette un username simile a quello giusto lascia entrare ma giustamente non mostra nulla, bisogna perciò fare in modo di bloccare l'accesso.
- [x] Nella modifica dei privilegi quando si seleziona un solo amministratore e gli si modifica il ruolo, se poi lo si elimina rimane visibile il pulsante di conferma modifica del permesso, sarebbe da far sparire quando l'amministratore viene tolto.
- [x]  Nella funzionalità di associazione dei amministratori se si associa un amministratore già associato all'organizzazione corrente, appare il messaggio associazione effettuata, dovrebbe invece apparire il messaggio che dica che l'amministratore è già associato.   (penso che pero sia un problema lato BackEnd).

*NB: Manca da testare se un accesso autenticato fa incrementare il contatore delle presenze.*

**Comment by TommasoAzz** [comment]
> * [ ]   Nella funzionalità di associazione dei amministratori se si associa un amministratore già associato all'organizzazione corrente, appare il messaggio associazione effettuata, dovrebbe invece apparire il messaggio che dica che l'amministratore è già associato.   (penso che pero sia un problema lato BackEnd).

Se parli del binding e non della creazione probabilmente sì. Se non è un macello proviamo a sistemarlo.

**Comment by pheasant98** [comment]
> > * [ ]    Nella funzionalità di associazione dei amministratori se si associa un amministratore già associato all'organizzazione corrente, appare il messaggio associazione effettuata, dovrebbe invece apparire il messaggio che dica che l'amministratore è già associato.   (penso che pero sia un problema lato BackEnd).
> 
> Se parli del binding e non della creazione probabilmente sì. Se non è un macello proviamo a sistemarlo.

sì mi riferisco al binding
